### ISSUE TITLE
Incorrect registry key for "Triple DES 168"

### ISSUE THREAD

**Issue by pronichkin** [Crosse/SchannelGroupPolicy#2]
The registry key you set for "Triple DES 168" is "Triple DES 168/168." However, as per official Microsoft support article (https://support.microsoft.com/help/245030), this key name only applies to legacy (pre-Windows Vista) operating system. For modern OSes, the name of the key should be just "Triple DES 168"--i.e., without the tailing "/168."

**Comment by Crosse** [comment]
It's been a while since I've touched ADMX, so I'll need to think about how I want to fix this. Ideally I'd like to be able to set the key based on the operating system, so that pre-Vista OSes set the key "Triple DES 168/168" and Vista+ OSes set "Triple DES 168" instead, but I don't remember if I can do that properly. The other option is to blindly set both keys—whichever key isn't used by the platform won't harm anything by being there, I doubt. The third option would be to simply not care about pre-Vista platforms and simply fix the key name.

If you have any suggestions in the interim, please feel free to let me know and/or submit a pull request!

**Comment by pronichkin** [comment]
IIRC, pre-Vista cannot parse ADMX anyway, so it only makes sense to target Vista+

**Comment by Crosse** [comment]
Oh...right. Well, that makes this easier. I fixed this in bca46de.

Thank you for the review!
