### ISSUE TITLE
Empty options

### ISSUE THREAD

**Issue by jimbju** [Crosse/SchannelGroupPolicy#21]
Hi,

Thanks for providing these templates!
I have installed the templates on my lab DC. When I configure a GPO, both settings (".NET Framework 2 STrong Crypto" and ".NET Framework 4 Strong Crypto") shows under "SSL Configuration Settings". However, when I open the setting, the "options window" is empty.
My DC is Windows Server 2019 (schema version 88). Did anyone try these templates on a Windows Server 2019 Domain Controller?

**Comment by Crosse** [comment]
If I had to guess, the `supportedOn` values for these settings may need to be updated. Currently they are set to:

.NET 2:
https://github.com/Crosse/SchannelGroupPolicy/blob/4902f2462ca37eae35fcb3d8c7c8140f2aa82059/template/schannel.admx#L987

.NET 4:
https://github.com/Crosse/SchannelGroupPolicy/blob/4902f2462ca37eae35fcb3d8c7c8140f2aa82059/template/schannel.admx#L935

It's been a long time since I've used Windows in a capacity where I've been able to use these GPOs, so it might take me a minute to figure out which Windows versions these settings should apply to, and the relevant/correct `supportedOn` values, but I'll see what I can find.

**Comment by jimbju** [comment]
Hi, I must have made a mistake when copying the content of the templates to my DC. All is working fine on a Windows 2019 DC.

**Comment by Crosse** [comment]
Oh, that’s great to hear! I’m glad it’s working for you. Thanks for the update.
